name: dash_bot
description: >-
  A Discord bot with useful utilities for the dart_community server.
version: 0.0.1-wip
repository: https://github.com/dart-community/dash_bot

environment:
  sdk: ^3.2.0

dependencies:
  meta: ^1.11.0

dev_dependencies:
  night_raven_insight: ^1.0.0
  test: ^1.24.9
