name: dash_bot
description: >-
  A Discord bot with useful utilities for the dart_community server.
version: 0.0.1-wip
repository: https://github.com/dart-community/dash_bot

environment:
  sdk: ^3.3.0

dependencies:
  http: ^1.2.0
  json_annotation: ^4.9.0
  meta: ^1.14.0
  nyxx: ^6.2.1
  nyxx_commands: ^6.0.2
  nyxx_extensions: ^4.1.0
  petitparser: ^6.0.2
  recase: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  night_raven_insight: ^2.0.0
  test: ^1.25.0
